### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by marr3n** [IonicaBizau/reset-your-facebook-account#12]
Hi,

the Chrome Extension link seems to be a broken link. 

Cheers..

**Comment by azimut** [comment]
Might be better link the github repo which won't change: https://github.com/attilathedud/jQueryInjector

**Comment by IonicaBizau** [comment]
Whoups, totally missed this issue. Yes, or maybe a link to a similar *good* extension.

**Comment by r4dian** [comment]
You can also just paste all of jquery into the console ...
