### ISSUE TITLE
[FIX]: Clear timeline

### ISSUE THREAD

**Issue by dtnmr** [IonicaBizau/reset-your-facebook-account#13]
Hi, and by the way thanks for this repository, it's been really helpful to me !

Everything worked fine for me except the "Clean Timeline" part, apparently the targeted aria-attribute is not here anymore.

Here's an updated version targeting a data attribute instead

```js
setInterval (function () {
  $("html, body").animate({ scrollTop: $(document).height() }, "slow");
  $('*[data-tooltip-content="Hidden from Timeline"]').each(function () {
    $(this).parents('.bottomborder').remove();
  });
  var allowed = $('*[data-tooltip-content="Allowed on Timeline"] span').last();
  allowed.click();
  $('.uiContextualLayer').find('li:nth-child(2)').find('a span').click();
  allowed.parents('.bottomborder').remove();
}, 400);
```

Have a nice day :)

**Comment by IonicaBizau** [comment]
Thanks, @dtnmr! :sparkles: 

Can you create a pull request with that?

Thanks!
