### ISSUE TITLE
Storing content prior to deletion

### ISSUE THREAD

**Issue by mgorenstein** [IonicaBizau/reset-your-facebook-account#17]
Have you considered expanding these scripts to append each item to an array or dictionary, allowing those entries to be saved to file at the end of a script's execution? I'm interested in archiving my activity prior to deletion. 

I haven't fiddled much with jQuery recently, but will experiment and report back if successful.

**Comment by mgorenstein** [comment]
I've stumbled upon a partial solution.

I execute the following:

`window.setInterval(function(){scrollBy(0,2000);}, 700);`

to auto-scroll in Chrome until FB loads no more content, then create a PDF from the print dialogue. Unfortunately, the generated document is effectively a massive screenshot (135MB, not text-searchable).

If you've any insight, @IonicaBizau, into a straightforward way to extract the content of each activity log item, I (and surely many others) would be much indebted.

**Comment by IonicaBizau** [comment]
Do the same thing and save the page as HTML. It's going to save it in a good enough result.

These scripts do not save your content.

**Comment by mgorenstein** [comment]
At least with Chrome, the results of saving HTML have not been very good. I'm working now with the mobile version of the activity log and should have better results after I determine a method to automate expanding the entire activity history.

**Comment by IonicaBizau** [comment]
There's a way to download your archive, tho I think that doesn't include your posts. Just in case it's useful (and you don't know that): https://www.facebook.com/help/131112897028467

**Comment by mgorenstein** [comment]
Thanks, @IonicaBizau. As you note, FB's download feature only provides a subset of content available in the activity log. 

I think I will be successful with the mobile version of the activity log (https://m.facebook.com/USERNAME/allactivity). 

Executing `$( "div[id*='m_timeline_loading_div']" ).click()`seems to be properly expanding the date-nodes (e.x. 'February 2016'), though sometimes the request initiated by the click() fails. Probably I will have to stagger the click() calls.
