### ISSUE TITLE
help with hacking

### ISSUE THREAD

**Issue by jerseyneue** [IonicaBizau/reset-your-facebook-account#19]
i'm not an engineer by any standard, and even with some basic web dev foundations for design, I don't have much exposure to js. 

I was hoping you could provide a little guidance with the "start hacking" step of the readme. 

i've got node installed
i've got npm installed
i've got the chrome extension working

i'm not sure how to actually run the scripts. i link to the fb page, inject the jquery (//code.jquery.com/jquery-3.2.1.min.js)

I've got terminal open (macOS Sierra 10.12.6). what do I do next?

**Comment by Nicofisi** [comment]
You don't need node, you don't need npm, you don't need a terminal

1. Install some chrome extension which injects jQuery
2. Copy one of the scripts
3. Go to one of the links in readme
4. `ctrl + shift + i` or `f12`
5. Paste the script to the console
6. Voila done
