### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by alvaromb** [IonicaBizau/reset-your-facebook-account#23]
Should be noted that current scripts works only with english language.

Can send a PR for that if you want.

**Comment by IonicaBizau** [comment]
Maybe a change mentioning that they have to modify the texts in their own language (if not English) would be nice to have.

Those who run these scripts should have the understanding of what's going on.

**Comment by alvaromb** [comment]
Ok. How do you feel about a notice in the [Prerequisites](https://github.com/IonicaBizau/reset-your-facebook-account#prerequisites) section? Or maybe below it?
