### ISSUE TITLE
Its not working on new facebook update.

### ISSUE THREAD

**Issue by abdulnine7** [IonicaBizau/reset-your-facebook-account#27]
Tried first script in README, this was the result.

Uncaught Error: <![EX[["Tried to get element with id of \"%s\" but it is not present on the page TAAL[1]","html, body"]]]>
    at g (pKYpBwo-oVi.js?_nc_x=pJNzjDsKcxy:115)
    at a (pKYpBwo-oVi.js?_nc_x=pJNzjDsKcxy:115)
    at <anonymous>:1:1
g @ pKYpBwo-oVi.js?_nc_x=pJNzjDsKcxy:115
a [from $-core] @ pKYpBwo-oVi.js?_nc_x=pJNzjDsKcxy:115
(anonymous) @ VM263:1

**Comment by ramuta** [comment]
It works, you just didn't inject jQuery properly. Make sure to first open Developer tools and then click on the Inject button in the jQuery Injector. You should see a sentence in the Developer tools console saying that jQuery has been injected. After that everything will work correctly.

**Comment by mlsem** [comment]
I just tested some of this requests on firefox and on chrome and its not working , maybe you could add a doc explaining how you are using this jquery injections ?

Thanks.

**Comment by ramuta** [comment]
> I just tested some of this requests on firefox and on chrome and its not working , maybe you could add a doc explaining how you are using this jquery injections ?
> 
> Thanks.

@mlsem check these instructions: https://github.com/ramuta/reset-your-facebook-account#instructions

**Comment by mlsem** [comment]
I already did that, but it's not deleting.
<img width="666" alt="Screenshot 2020-03-21 at 11 11 36" src="https://user-images.githubusercontent.com/11228017/77224352-fe906900-6b64-11ea-8e54-38e13e0efd5d.png">

**Comment by ramuta** [comment]
> I already did that, but it's not deleting.
> <img alt="Screenshot 2020-03-21 at 11 11 36" width="666" src="https://user-images.githubusercontent.com/11228017/77224352-fe906900-6b64-11ea-8e54-38e13e0efd5d.png">

Is this for deleting comments?

Can you check this updated code (the second block): https://github.com/ramuta/reset-your-facebook-account#comments

**Comment by mlsem** [comment]
seems working with this new script, thanks, I think we have the same issue with likes , I will double check that.

**Comment by mlsem** [comment]
I return back to check my comments and its all there , no comment was deleted
