### ISSUE TITLE
enhancement: snippets to clear specific categories of activity records (for new facebook interface)

### ISSUE THREAD

**Issue by Lin2Jing4** [IonicaBizau/reset-your-facebook-account#32]
As required by the [contributing guidelines](https://github.com/IonicaBizau/reset-your-facebook-account/blob/6a13c7f9f4070bca522de0889dab81b5f444e5f1/CONTRIBUTING.md), I am here describing the contribution I would like to make:
- There are JS snippets for the new facebook interface that can be used to clear specific categories of activity records.
- The following draft PR's have been fully tested and are ready to be opened:
  - [posts](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/posts)
  - [remove-reactions](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/remove-reactions)
  - [comments](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/comments)
  - [photos](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/photos)
  - [others'-posts-to-your-timeline](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/others'-posts-to-your-timeline)
  - [hidden-stories](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/hidden-stories)
  - [profile-change-logs](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/profile-change-logs)
  - [videos-you've-watched](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/videos-you've-watched)
  - [following-records](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/following-records)
  - [groups-activities](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/groups-activities)
  - [membership-activities](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/membership-activities)
  - [group-posts-and-comments](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/group-posts-and-comments)
  - [event-invitations](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/event-invitations)
  - [event-responses](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/event-responses)
  - [poll-votes](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/poll-votes)
  - [search-history](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/search-history)
  - [search-history-for-groups](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/search-history-for-groups)
  - [saved-for-later](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/saved-for-later)
  - [other-records](https://github.com/Lin2Jing4/reset-your-facebook-account/tree/fix/other-records)
- Maintainers and contributors can discuss here when to open these 19 PR's and how to merge them.
- For the sake of convenience, I added @IonicaBizau as a collaborator to have write access to [my forked repository](https://github.com/Lin2Jing4/reset-your-facebook-account).

**Comment by IonicaBizau** [comment]
@Lin2Jing4 Sorry for the late reply. Can you please create a PR with all these changes? We will be happy to merge it. 🍀
