### ISSUE TITLE
Post Privacy Public to Only me

### ISSUE THREAD

**Issue by lovebdsobuj** [IonicaBizau/reset-your-facebook-account#8]
I want to change post privacy Public to Only me, with your code possible do something?

**Comment by IonicaBizau** [comment]
Well, you don't need a script for that. Go to the Timeline settings and set it:

![image](https://cloud.githubusercontent.com/assets/2864371/13031778/e304de4e-d2e0-11e5-8933-e08a3e58ea81.png)

Hope it helps. :grin:

**Comment by lovebdsobuj** [comment]
This is not my question answer. I'm not about Tagged post privacy. I'm taking about my timeline self posted privacy. But I forgot to say **Past Post Privacy**.

**Comment by IonicaBizau** [comment]
Oh, sorry! I misunderstood.

**Comment by lovebdsobuj** [comment]
It's okay sir...

**Comment by IonicaBizau** [comment]
We can set up a script that will select the "Only me" option in the posts page.

**Comment by lovebdsobuj** [comment]
Do tech me, how to write this like code, what is the finding method?
Then I'll try also...

**Comment by lovebdsobuj** [comment]
Sir, what about this, it's your **Public Contributions** Screen.
![screenshot_00118_16h32m43s](https://cloud.githubusercontent.com/assets/10352682/13033245/ac401636-d339-11e5-9f1d-bf47c8d1b68e.png)

**Comment by IonicaBizau** [comment]
Currently I'm a bit busy, but take a look at the examples.

You have to go to the posts page (`https://www.facebook.com/IonicaBizau/allactivity?privacy_source=activity_log&log_filter=cluster_11`—replace `IonicaBizau` with your Facebook username) and then write some code to click on the select boxes and then click "Only Me". :sparkle:

**Comment by IonicaBizau** [comment]
> Sir, what about this, it's your Public Contributions Screen.

Haha, check [this](https://github.com/IonicaBizau/github-contributions) out. :joy:

**Comment by lovebdsobuj** [comment]
Maybe, It's hard to understand me. 
> and then write some code

here some code mean? 

What some code refers to...

**Comment by IonicaBizau** [comment]
@lovebdsobuj In the developer tools, write the code you want to execute on the page, similar to what you see in the README file of this repository.
